
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: "mysql://avnadmin:AVNS_nYGWUQ2e8YKHr1ut_vu@rbac-mysql-rbac.k.aivencloud.com:11409/defaultdb?ssl-mode=REQUIRED"
  },
});
